### ISSUE TITLE
Hallo Kevin

### ISSUE THREAD

**Issue by rtmx-offiziell** [JacobDev1/genshin_timer#1]
Hallo Kevin oder Sakana da du mich blockiert hast, möchte ich hier dir gerne sagen das dieses Verhalten zu einem 11 Jahren Menschen sehr passt aber meinen DC Server voll zu späten ist nicht richtig, bitte unblockieren mich dann kann ich dir noch was schreiben

Vielen Dank 
RTMX ist ein Projekt von MAX6025.com & Max6025.org
Haupt Projekt RTMX.org

Diesen Inhalt hat Max6025 (Leitung) geschrieben

**Comment by JacobDev1** [comment]
Hello,

You are reaching out to the wrong person. My name is not Kevin, and I have never met or messaged you.

My official email is publicly available on my GitHub profile and my website. GitHub Issues is meant to be used for project specific problems.
